openapi: 3.0.0
info:
  title: Health2 Restful Service # VAR5(服務名稱): 從 info.title 讀取
  version: 1.0.0
  description: 健康檢查 API 文件

servers:
  - url: http://192.168.31.180:5678 # VAR3(上游地址): 從 servers[0].url 提取 host:port

paths:
  /api/v1/health: # VAR2(轉發上游路徑): 從 first.paths 提取的 path
    get:
      summary: health2 # VAR1(請求路徑): /{prefix}/{summary}
      description: 取得健康檢查資訊
      tags:
        - health
      responses:
        "200":
          description: 成功取得健康檢查資訊
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: ok
        message:
          type: string
          example: Service is healthy
