openapi: 3.0.0
info:
  title: Health Restful Service
  version: 1.0.0
  description: 健康檢查 API 文件

servers:
  - url: http://192.168.31.180:5678/api/v1/health

paths:
  /health:
    get:
      summary: health
      description: 取得健康檢查資訊
      tags:
        - health
      responses:
        "200":
          description: 成功取得健康檢查資訊
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: ok
        message:
          type: string
          example: Service is healthy
