apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apipark.apinto.fullname" . }}-config
  labels:
    {{- include "apipark.labels" . | nindent 4 }}
    app.kubernetes.io/component: apinto
data: 
  config.yml: |
    version: 2
    client:
      listen_urls: # open api 服務的監聽位址
        - http://0.0.0.0:9400
    gateway:
      # advertise_urls: # 轉送服務的廣播位址
      #   - http://127.0.0.1:9400
      listen_urls: # 轉送服務的監聽位址
        - https://0.0.0.0:8099
        - http://0.0.0.0:8099
    peer: # 集群間節點通訊設定資訊
      listen_urls: # 節點監聽位址
        - http://0.0.0.0:9401

  apinto.yml: |
    # 資料檔案放置目錄
    data_dir: /var/lib/apinto
    # pid檔案放置位址
    pid_dir: /var/run/apinto/
    # 日誌放置目錄
    log_dir: /var/log/apinto
    # socket放置目錄
    socket_dir: /tmp/apinto
    # apinto運行設定位址
    config: /etc/apinto/config.yml
    # 擴充倉庫目錄
    extends_dir: /var/lib/apinto/extenders/
    # 錯誤日誌檔名
    error_log_name: error.log
    # 錯誤日誌等級，日誌等級可以劃分為：debug，info，warn，error，panic五個等級，預設等級為error
    error_log_level: debug
    # 錯誤日誌過期時間，預設單位為天，d|天，h|小時
    error_log_expire: 7d
    # 錯誤日誌切割週期，僅支援day、hour
    error_log_period: day
