{{- if and .Values.apinto.enabled .Values.apinto.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apipark.apinto.fullname" . }}-data-pvc
  labels:
    {{- include "apipark.labels" . | nindent 4 }}
    app.kubernetes.io/component: apinto
spec:
  accessModes:
    - {{ .Values.global.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.apinto.persistence.size }}
  {{- if .Values.global.persistence.storageClass }}
  storageClassName: {{ .Values.global.persistence.storageClass }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apipark.apinto.fullname" . }}-log-pvc
  labels:
    {{- include "apipark.labels" . | nindent 4 }}
    app.kubernetes.io/component: apinto
spec:
  accessModes:
    - {{ .Values.global.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.apinto.persistence.size }}
  {{- if .Values.global.persistence.storageClass }}
  storageClassName: {{ .Values.global.persistence.storageClass }}
  {{- end }}
{{- end }}
