{{- if and .Values.grafana.enabled .Values.grafana.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apipark.grafana.fullname" . }}-pvc
  labels:
    {{- include "apipark.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  accessModes:
    - {{ .Values.global.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
  {{- if .Values.global.persistence.storageClass }}
  storageClassName: {{ .Values.global.persistence.storageClass }}
  {{- end }}
{{- end }}
