apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apipark.grafana.fullname" . }}-config
  labels:
    {{- include "apipark.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
data:
  grafana-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://{{ include "apipark.fullname" . }}-loki:3100
