{{- if .Values.influxdb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apipark.influxdb.fullname" . }}
  labels:
    {{- include "apipark.labels" . | nindent 4 }}
    component: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "apipark.selectorLabels" . | nindent 6 }}
      component: influxdb
  template:
    metadata:
      labels:
        {{- include "apipark.selectorLabels" . | nindent 8 }}
        component: influxdb
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: influxdb
          image: "{{ .Values.influxdb.image.repository }}:{{ .Values.influxdb.image.tag }}"
          imagePullPolicy: {{ .Values.influxdb.image.pullPolicy }}
          ports:
            - name: influxdb
              containerPort: 8086
              protocol: TCP
          env:
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: {{ .Values.influxdb.auth.username | quote }}
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              value: {{ .Values.influxdb.auth.password | quote }}
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: {{ .Values.influxdb.auth.org | quote }}
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: {{ .Values.influxdb.auth.bucket | quote }}
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              value: {{ .Values.influxdb.auth.token | quote }}
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: "setup"
          volumeMounts:
            - name: influxdb-data
              mountPath: /var/lib/influxdb2
            - name: influxdb-config
              mountPath: /etc/influxdb2
          {{- with .Values.influxdb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: influxdb
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: influxdb
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: influxdb-data
          {{- if .Values.influxdb.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "apipark.influxdb.fullname" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: influxdb-config
          emptyDir: {}
{{- end }}
