{{- if .Values.ingress.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apipark.fullname" . }}-ingress-controller
  namespace: ingress-nginx
  labels:
    {{- include "apipark.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: {{ .Values.ingress.nodePorts.http | default 31288 }}
    - name: https
      port: 443
      targetPort: 443
      nodePort: {{ .Values.ingress.nodePorts.https | default 31306 }}
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apipark.fullname" . }}-mysql-nodeport
  labels:
    {{- include "apipark.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  type: NodePort
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: {{ .Values.ingress.nodePorts.mysql | default 31306 }}
  selector:
    {{- include "apipark.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "apipark.fullname" . }}
  labels:
    {{- include "apipark.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .service.name }}
                port:
                  number: {{ .service.port }}
          {{- end }}
    {{- end }}
{{- end }}
