{{- if .Values.loki.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apipark.loki.fullname" . }}
  labels:
    {{- include "apipark.labels" . | nindent 4 }}
    component: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "apipark.selectorLabels" . | nindent 6 }}
      component: loki
  template:
    metadata:
      labels:
        {{- include "apipark.selectorLabels" . | nindent 8 }}
        component: loki
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: loki
          image: "{{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag }}"
          imagePullPolicy: {{ .Values.loki.image.pullPolicy }}
          command:
            - /usr/bin/loki
            - -config.file=/etc/loki/loki-config.yaml
          ports:
            - name: loki
              containerPort: 3100
              protocol: TCP
          volumeMounts:
            - name: loki-data
              mountPath: /tmp/loki
            - name: loki-config
              mountPath: /etc/loki
          {{- with .Values.loki.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /ready
              port: loki
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: loki
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: loki-data
          {{- if .Values.loki.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "apipark.loki.fullname" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: loki-config
          configMap:
            name: {{ include "apipark.fullname" . }}-shared-config
{{- end }}
