{{- if and .Values.loki.enabled .Values.loki.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apipark.loki.fullname" . }}-pvc
  labels:
    {{- include "apipark.labels" . | nindent 4 }}
    component: loki
spec:
  accessModes:
    - {{ .Values.loki.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.loki.persistence.size }}
  {{- if .Values.loki.persistence.storageClass }}
  storageClassName: {{ .Values.loki.persistence.storageClass }}
  {{- end }}
{{- end }}
