{{- if .Values.loki.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apipark.loki.fullname" . }}
  labels:
    {{- include "apipark.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki
spec:
  type: {{ .Values.loki.service.type }}
  ports:
    - port: {{ .Values.loki.service.port }}
      {{- if .Values.loki.service.targetPort }}
      targetPort: {{ .Values.loki.service.targetPort }}
      {{- end }}
      protocol: TCP
      name: loki
      {{- if eq .Values.loki.service.type "NodePort" }}
      nodePort: {{ .Values.loki.service.nodePort }}
      {{- end }}
  selector:
    {{- include "apipark.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: loki
{{- end }}
