{{- if .Values.nsq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apipark.nsq.fullname" . }}
  labels:
    {{- include "apipark.labels" . | nindent 4 }}
    app.kubernetes.io/component: nsq
spec:
  type: {{ .Values.nsq.service.type }}
  ports:
    - name: tcp
      port: {{ .Values.nsq.service.ports.tcp.port }}
      {{- if .Values.nsq.service.ports.tcp.targetPort }}
      targetPort: {{ .Values.nsq.service.ports.tcp.targetPort }}
      {{- end }}
      protocol: TCP
    - name: http
      port: {{ .Values.nsq.service.ports.http.port }}
      {{- if .Values.nsq.service.ports.http.targetPort }}
      targetPort: {{ .Values.nsq.service.ports.http.targetPort }}
      {{- end }}
      protocol: TCP
  selector:
    {{- include "apipark.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nsq
{{- end }}
