apiVersion: v2
name: apipark
description: APIPark - API Management Platform
type: application
version: 1.9.5-beta
appVersion: "1.9.5-beta"
keywords:
  - api
  - management
  - gateway
  - microservices
home: https://github.com/APIParkLab/APIPark
sources:
  - https://github.com/APIParkLab/APIPark
maintainers:
  - name: APIPark Team
    email: contact@apipark.com
dependencies: []
