apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apipark-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: rpa-local-storage